name: 'Caffeine Language GitHub Action'
description: 'GitHub Action for Caffeine Language'
author: 'Brickell Research'

branding:
  icon: 'activity'
  color: 'green'

inputs:
  version:
    description: 'Caffeine version to use'
    required: true
    default: 'latest'
  args:
    description: 'Arguments to pass to the Caffeine command'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.args }}
