name: 'caffeine_lang'
description: 'Run caffeine_lang as part of your GitHub Actions workflows'
author: 'Your Organization'

inputs:
  args:
    description: 'Arguments to pass to caffeine_lang'
    required: true
  version:
    description: 'Version of caffeine_lang to install (e.g., v1.2.3)'
    required: false
    default: 'latest'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
